server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tb_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
      prefix: classpath:/templates/
  jackson:
    date-format: yyyy-MM-d HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    time-out: 3000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.leo.taobao.entity


